# Generated by Django 4.0.4 on 2022-06-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
